import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Layout from '@/components/Layout'
import SEO from '@/components/SEO'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Layout>
          <SEO 
            title={process.env.siteTitle || 'Glasgow Books'}
          />
          {children}
        </Layout>
      </body>
    </html>
  )
}
